# -*- encoding: utf-8 -*-

=begin
#Clever API

#The Clever API

OpenAPI spec version: 3.1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.68
=end

$:.push File.expand_path("../lib", __FILE__)
require "clever-ruby-v3/version"

Gem::Specification.new do |s|
  s.name        = "clever-ruby-v3"
  s.version     = CleverV3::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["Swagger-Codegen"]
  s.email       = [""]
  s.homepage    = "https://github.com/swagger-api/swagger-codegen"
  s.summary     = "Clever API Ruby Gem"
  s.description = "The Clever API"
  s.license     = "Unlicense"
  s.required_ruby_version = ">= 1.9"

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'
  s.add_runtime_dependency 'json', '~> 2.1', '>= 2.1.0'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = Dir['{lib,spec}/**/*'] + ['README.md']
  s.test_files    = Dir['spec/**/*']
  s.executables   = []
  s.require_paths = ["lib"]
end
