=begin
#Clever API

#The Clever API

OpenAPI spec version: 3.1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.68
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Clever::ResourceResponse
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ResourceResponse' do
  before do
    # run before each test
    @instance = Clever::ResourceResponse.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ResourceResponse' do
    it 'should create an instance of ResourceResponse' do
      expect(@instance).to be_instance_of(Clever::ResourceResponse)
    end
  end
  describe 'test attribute "data"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
