=begin
#Clever API

#The Clever API

OpenAPI spec version: 3.1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.68
=end

# Common files
require 'clever-ruby-v3/api_client'
require 'clever-ruby-v3/api_error'
require 'clever-ruby-v3/version'
require 'clever-ruby-v3/configuration'

# Models
require 'clever-ruby-v3/models/bad_request'
require 'clever-ruby-v3/models/contact'
require 'clever-ruby-v3/models/course'
require 'clever-ruby-v3/models/course_object'
require 'clever-ruby-v3/models/course_response'
require 'clever-ruby-v3/models/courses_created'
require 'clever-ruby-v3/models/courses_deleted'
require 'clever-ruby-v3/models/courses_response'
require 'clever-ruby-v3/models/courses_updated'
require 'clever-ruby-v3/models/credentials'
require 'clever-ruby-v3/models/district'
require 'clever-ruby-v3/models/district_admin'
require 'clever-ruby-v3/models/district_contact'
require 'clever-ruby-v3/models/district_object'
require 'clever-ruby-v3/models/district_response'
require 'clever-ruby-v3/models/districts_created'
require 'clever-ruby-v3/models/districts_deleted'
require 'clever-ruby-v3/models/districts_response'
require 'clever-ruby-v3/models/districts_updated'
require 'clever-ruby-v3/models/event'
require 'clever-ruby-v3/models/event_response'
require 'clever-ruby-v3/models/events_response'
require 'clever-ruby-v3/models/internal_error'
require 'clever-ruby-v3/models/link'
require 'clever-ruby-v3/models/location'
require 'clever-ruby-v3/models/name'
require 'clever-ruby-v3/models/not_found'
require 'clever-ruby-v3/models/principal'
require 'clever-ruby-v3/models/resource'
require 'clever-ruby-v3/models/resource_object'
require 'clever-ruby-v3/models/resource_response'
require 'clever-ruby-v3/models/resources_created'
require 'clever-ruby-v3/models/resources_deleted'
require 'clever-ruby-v3/models/resources_response'
require 'clever-ruby-v3/models/resources_updated'
require 'clever-ruby-v3/models/roles'
require 'clever-ruby-v3/models/school'
require 'clever-ruby-v3/models/school_enrollment'
require 'clever-ruby-v3/models/school_object'
require 'clever-ruby-v3/models/school_response'
require 'clever-ruby-v3/models/schools_created'
require 'clever-ruby-v3/models/schools_deleted'
require 'clever-ruby-v3/models/schools_response'
require 'clever-ruby-v3/models/schools_updated'
require 'clever-ruby-v3/models/section'
require 'clever-ruby-v3/models/section_object'
require 'clever-ruby-v3/models/section_response'
require 'clever-ruby-v3/models/sections_created'
require 'clever-ruby-v3/models/sections_deleted'
require 'clever-ruby-v3/models/sections_response'
require 'clever-ruby-v3/models/sections_updated'
require 'clever-ruby-v3/models/staff'
require 'clever-ruby-v3/models/student'
require 'clever-ruby-v3/models/student_relationship'
require 'clever-ruby-v3/models/teacher'
require 'clever-ruby-v3/models/term'
require 'clever-ruby-v3/models/term_object'
require 'clever-ruby-v3/models/term_response'
require 'clever-ruby-v3/models/terms_created'
require 'clever-ruby-v3/models/terms_deleted'
require 'clever-ruby-v3/models/terms_response'
require 'clever-ruby-v3/models/terms_updated'
require 'clever-ruby-v3/models/user'
require 'clever-ruby-v3/models/user_object'
require 'clever-ruby-v3/models/user_response'
require 'clever-ruby-v3/models/users_created'
require 'clever-ruby-v3/models/users_deleted'
require 'clever-ruby-v3/models/users_response'
require 'clever-ruby-v3/models/users_updated'

# APIs
require 'clever-ruby-v3/api/data_api'
require 'clever-ruby-v3/api/events_api'

module Clever
  class << self
    # Customize default settings for the SDK using block.
    #   Clever.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
